server:
  port: 8080
spring:
  application:
    name: ggnetwork
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/ggnetwork
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
app:
  token:
    secret: 1234
    duration:
      days: 2